### ISSUE TITLE
提几点小建议

### ISSUE THREAD

**Issue by chengqiang1992** [BboyAwey/auto-unit-test-testing#1]
> * 3.2.2 初始化Karma配置文件  在win10平台下  karma init 之前应该先 [npm install -g karma-cli](http://stackoverflow.com/questions/20800933/running-karma-after-installation-results-in-karma-is-not-recognized-as-an-inte)
> * 3.2.2 初始化Karma配置文件  在win10平台下 karma init最好先在本地目录下建好 src 和 test文件夹
> * 最好，好像TMD Mocha语法变了，搞了两个多小时这个demo还是没跑起来，WC

**Comment by BboyAwey** [comment]
感谢，文章写完到现在有时日了，我会酌情更新

**Comment by BboyAwey** [comment]
不过思路是不变的，我写这个文章主要是为了阐明单元测试的思路和做法，具体API的用法不是文章重点，给你造成不便请见谅

**Comment by chengqiang1992** [comment]
你太客气啦   没有不便  没有不便   哈哈
